name: NuEngine CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DNU_BUILD_TESTS=ON
          -DNU_BUILD_EDITOR=OFF
          -DNU_BUILD_BENCHMARKS=OFF

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --target ALL_BUILD

      - name: Run tests
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure --timeout 300